server:
  port: 8008
spring:
  application:
    name: rockermq-producer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    stream:
      rocketmq:
        binder:
          name-server: 192.168.26.231:9876;192.168.26.232:9876
      bindings:
        output:
          destination: test-topic
          content-type: application/json
        input:
          destination: test-topic
          content-type: text/plain
#          content-type: application/json
          group: test-group