server:
  port: 8007
spring:
  application:
    name: rockermq-consumer
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      bindings:
        output:
          destination: test-topic
          content-type: application/json
        input:
          destination: test-topic
          content-type: text/plain
#          content-type: application/json
          group: test-group